import type { GameDataItem, Character } from "../types";
import {
  WitnessIcon,
  EvidenceIcon,
  // LocationIcon,
  ForensicsIcon,
} from "../components/icons/StaticIcons";

export const charactersData: Character[] = [
  {
    id: "mahesa",
    name: "Mahesa Andi D.",
    role: "Teman Kerja",
    description: "Rekan kerja Helda yang memiliki hubungan dekat.",
    imageUrl: "/C001.webp",
  },
  {
    id: "arief",
    name: "Arief M.",
    role: "Pekerja Kebun",
    description: "Tukang rumput yang sering bekerja di rumah Helda dan Dimas.",
    imageUrl: "/C002.webp",
  },
  {
    id: "dimas",
    name: "Dimas Prakasa",
    role: "Suami",
    description: "Suami dari Helda, korban pembunuhan.",
    imageUrl: "/C005.webp",
  },
  {
    id: "larasati",
    name: "Larasati",
    role: "ART Keluarga",
    description: "Asisten Rumah Tangga yang bekerja untuk Helda dan Dimas.",
    imageUrl: "/C007.webp",
  },
  {
    id: "lastri",
    name: "Ibu Lastri",
    role: "Tetangga",
    description: "Tetangga di sekitar rumah kejadian.",
    imageUrl: "/C008.webp",
  },
  {
    id: "risa",
    name: "Risa",
    role: "Istri Arief",
    description: "Istri dari Arief M.",
    imageUrl: "/C009.webp",
  },
  {
    id: "reivan",
    name: "Reivan Pratama",
    role: "Pemilik Toko \"Kings Spray Cans\"",
    description: "Berawal dari kecintaannya pada street art, Reivan akhirnya berhasil mengembangkan merek cat semprot (pilox) miliknya sendiri. Toko pertamanya, \"Kings Spray Cans\", resmi didirikan lima tahun lalu dengan memanfaatkan kediaman pribadinya sebagai toko.",
    imageUrl: "/reivann.png",
  },
  {
    id: "rabhya",
    name: "Rabhya Wibowo",
    role: "Tukang Furnitur Paruh Waktu",
    description: "Pak Rabhya adalah tokoh masyarakat di Komplek Pelita yang telah menjabat sebagai Ketua RT selama tiga periode. Karir kepemimpinannya dimulai saat ia masih aktif di militer. Pada usianya yang ke-43 tahun, Pak Rabhya terpaksa diberhentikan sebab luka serius yang dialaminya saat bertugas. Pak Rabhya adalah individu yang rela berkorban dan selalu memastikan dirinya dapat berdampak ke lingkungan. Dirinya beranggapan bahwa ia selalu tahu apa yang terbaik bagi orang-orang sebab kepemimpinannya yang selalu disanjung selama ini.",
    imageUrl: "/rabhya.png",
  },
  {
    id: "adinata",
    name: "Adinata Agung",
    role: "Pebisnis",
    description: "Pak Adinata adalah warga pelita yang dikenal dengan kepercayaan dirinya yang tinggi. Selain itu, Pak Adinata juga memiliki kharisma yang bisa membuat semua percaya padanya. Alasan inilah yang akhirnya mendorong beberapa warga untuk mendukung Pak Adinata sebagai Ketua RT yang baru.",
    imageUrl: "/adinata.png",
  },
  {
    id: "luthfi",
    name: "Cahaya Luthfi Darmawan",
    role: "Seniman Street Art",
    description: "Luthfi adalah penghuni baru di Komplek Pelita. Ia menempati kediamannya sekarang setelah menerima ajakan dari kawan masa kecilnya, Bara. Berbeda dengan teman sekamarnya, Luthfi memiliki kepribadian yang pendiam, pemalu, dan tutur kata yang halus. Meski secara usia lebih tua, ia sudah terbiasa mengikuti arahan Bara dalam segala hal.",
    imageUrl: "/luthfi.png",
  },
  {
    id: "chantika",
    name: "Angelina Chantika",
    role: "Ibu Rumah Tangga",
    description: "Ratu gosip Komplek Pelita yang punya segudang cerita tentang seluruh warga. Ia merasa tahu segalanya, mulai dari sejarah keluarga hingga konflik terbaru di setiap rumah. Hati-hati kalau melihatnya sedang \"santai\" di depan rumah orang, karena kemungkinan besar ia sedang menunggu waktu yang tepat untuk menguping informasi terbaru.",
    imageUrl: "/chantika.png",
  },
  {
    id: "ratu",
    name: "Ratu Ningtyas Sekarya",
    role: "Ibu Rumah Tangga",
    description: `Sebagai istri Ketua RT, Ibu Ratu terobsesi pada martabat keluarga hingga sering kali bersikap julid dan sinis terhadap warga yang dianggapnya mengganggu. Ia kerap memuji sosok Abyaz di depan orang lain, meski ia sendiri kecewa dengan perilaku asli anaknya. Hal ini menciptakan konflik antara ibu dan anak di rumah, yang biasanya diredam oleh Pak Rabhya.`,
    imageUrl: "/ratu.png",
  },
  {
    id: "damali",
    name: `Damali Nasya`,
    role: "Ibu Rumah Tangga",
    description: `Bu Damali sering dianggap aneh dan paranoid oleh warga sekitar, bahkan terdapat rumor tentang dirinya yang memiliki gangguan jiwa. Padahal, ia hanyalah sosok dengan ketertarikan pada fenomena yang dianggap mustahil oleh orang awam. Bu Damali memiliki kesulitan berbaur karena cara pandangnya yang unik. Namun, kehadiran suaminya sangat membantu Bu Damali untuk menyampaikan apa yang ia pikirkan.`,
    imageUrl: "/damali.png",
  },
  {
    id: "bara",
    name: `Bara Gumelang`,
    role: "Seniman Street Art",
    description: `Bara adalah warga Pelita yang baru saja kembali dari kampung halamannya dan menempati rumah bernomorkan empat puluh dua setelah kepergian Sang Ibu. Bara adalah individu yang terus terang dan mudah emosi, tampilannya nyentrik karena kesukaannya terhadap budaya punk. Perlawanan yang sangat kental pada budaya ini ia tuangkan pada setiap karya sebagai seorang seniman street art.`,
    imageUrl: "/bara.png",
  },
  {
    id: "andos",
    name: `Andos Sihombing`,
    role: "Pebisnis dan Aktivis Lingkungan",
    description: `Andos, putra dari Bu Malo, adalah seorang pebisnis sukses yang membangun karirnya atas dasar kecintaan terhadap lingkungan. Ia dikenal sebagai sosok yang sangat produktif dan selalu mengisi hari-harinya dengan berbagai kegiatan bermanfaat. Tak heran, saat diberi kepercayaan untuk menjadi Ketua Pengelola TPS di lingkungannya, ia menyambutnya dengan antusias demi mewujudkan lingkungan yang lebih asri.`,
    imageUrl: "/andos.png",
  },
  {
    id: "abyaz",
    name: `Abyaz Mahendra Wibowo`,
    role: "Mahasiswa",
    description: `Abyaz, mahasiswa tingkat akhir jurusan musik, dikenal pendiam dan selalu bersembunyi di balik gaya rocker serba gelapnya. Di rumah, ia menjadi titik tengah konflik: target kritik tajam Ibu Ratu namun selalu dibela oleh Pak Rabhya. Ketidaksukaannya pada standar tinggi sang ibu membuat Abyaz sangat loyal kepada ayahnya.`,
    imageUrl: "/abyaz.png",
  },

];

// This acts as a database of all scannable items in the game.
// The key is the string that the QR code will contain.
const gameData: Record<string, Omit<GameDataItem, "id">> = {
  MAHESA_ANDI_D: {
    type: "Saksi",
    title: "Mahesa Andi D.",
    subtitle: "Teman Kerja",
    imageUrl: "/C001.webp",
    content:
      "Andi mengonfirmasi bahwa setelah menyelesaikan urusan dinas, mereka berdua singgah di rumah kedua milik Helda, yang biasa digunakan untuk kebutuhan dinas. Andi menyatakan, pada malam 9 November 2011, sekitar pukul 23.00 WIB, terjadi pertengkaran hebat antara dirinya dan Helda di rumah tersebut. Pertengkaran itu dipicu oleh janji Helda untuk meninggalkan suaminya yang tak kunjung ditepati, yang membuat Sdr. Andi sangat emosi dan lelah. Namun, Andi bersumpah bahwa ia tidak mungkin sekeji itu menghabisi Helda.\n\nSekitar pukul 23.30 WIB, ia meninggalkan Helda sendirian di rumah tersebut karena kesal dan frustasi, lalu langsung pulang ke kediamannya di Pancoran. Ia tiba pukul 00.30 WIB dini hari, 10 November 2011, dan dapat menunjukkan riwayat tol serta bukti e-toll perjalanannya dari Jakarta Utara menuju Pancoran.",
    icon: WitnessIcon,
    characterId: "mahesa",
    isAlibi: true,
    audioUrl: "/audio/mahesa.mp3",
  },
  ARIEF_M: {
    type: "Tukang Rumput",
    title: "Arief M.",
    subtitle: "Pekerja Kebun",
    imageUrl: "/C002.webp",
    content:
      "Arief menegaskan bahwa ia tidak bekerja atau mengunjungi rumah kedua Helda dan Dimas pada hari Rabu, 9 November 2011 dan mengaku menghabiskan malam itu di rumahnya bersama keluarganya. Beberapa hari setelah penemuan jasad Ibu Helda diberitakan, Pak Dimas menelepon Arief dan memintanya untuk segera membersihkan rumput di halaman rumah. Meskipun ada rasa takut karena tragedi yang menimpa Helda, Mas Arief tetap datang.\n\nSaat bekerja di halaman depan rumah pada siang hari tanggal 15 November 2011, Mas Arief dapat mencium bau pewangi samar yang datang dari dalam rumah. Ia tidak berpikir aneh, tapi itu menjadi detail yang ingin ia sampaikan kepada penyidik.",
    icon: WitnessIcon,
    characterId: "arief",
    isAlibi: true,
    audioUrl: "/audio/voibu.mp3",
  },
  ARIEF_M_2: {
    type: "Tetangga",
    title: "Arief M",
    subtitle: "Pekerja Kebun", // Changed from Suami since Arief is Pekerja Kebun
    imageUrl: "/C004.webp",
    content: "Informasi tambahan dari Arief.",
    icon: WitnessIcon,
    characterId: "arief",
    isAlibi: false,
  },
  REIVAN: {
    type: "Pemilik Toko \"Kings Spray Cans\"",
    title: "Reivan Pratama",
    subtitle: "Pemilik Toko \"Kings Spray Cans\"",
    imageUrl: "/reivann.png",
    content: "Selamat datang-, oh investigasi mengenai malam Kamis? Sejujurnya, saya tidak terlalu mengikuti gosip di komplek ini. Malam itu saya hanya menjaga toko seperti biasanya. Waktu itu yang datang ke toko juga sedikit; remaja sekolah yang beli untuk merayakan kelulusan, ada juga mahasiswa dengan tampilan gelap dan rambut panjang ombre, ada juga bapak-bapak bertubuh kurus kering yang ingin membeli untuk mengecat furniturnya. Kami sebenarnya memiliki langganan setia toko bernama Bara dan Luthfi, sering kali saya memberikan cans gratis ke mereka. Namun, seingat saya, Bara dan Luthfi tidak kesini malam itu sebab minggu lalu mereka sudah belanja spray cans dengan jumlah yang banyak. ",
    icon: WitnessIcon,
    characterId: "reivan",
    isAlibi: false,
  },
  ANDOS: {
    type: "Pebisnis dan Aktivis Lingkungan",
    title: "Andos Sihombing",
    subtitle: "Pebisnis dan Aktivis Lingkungan",
    imageUrl: "/andos.png",
    content: `Jujur saja, Detektif, saya sangat terpukul. Hubungan saya dan Ibu belakangan memang kurang baik; kami sering bertengkar karena beliau tidak setuju saya menjabat sebagai Ketua Pengelola TPS. Ibu enggan melihat saya bekerja sama terlalu dekat dengan Pak Rabhya, padahal niat saya murni hanya ingin memperbaiki tatanan pengelolaan sampah di komplek ini.
Bagi saya, Pak Rabhya adalah sosok yang luar biasa. Beliau sendiri yang menunjuk saya karena kami memiliki visi dan misi yang sama soal lingkungan. Akibat perselisihan dengan Ibu, saya bahkan hanya pulang ke rumah untuk tidur saja selama dua minggu terakhir.
Lalu pada malam Kamis itu, saya memutuskan menginap di pos petugas karena ada mesin pengolah sampah yang rusak dan perlu diperbaiki. Mesin itu sudah mati seminggu, jadi saya harus memantau pengerjaannya semalaman bersama beberapa petugas lain. Saya sungguh menyesal.. seandainya malam itu saya ada di rumah, mungkin Ibu tidak akan menghilang begitu saja tanpa saya ketahui. (Silahkan buka kartu nomor 22)`,
    icon: WitnessIcon,
    characterId: "andos",
    isAlibi: true,
  },
  ANDOS2: {
    type: "Pebisnis dan Aktivis Lingkungan",
    title: "WAWANCARA 2",
    subtitle: "Pebisnis dan Aktivis Lingkungan",
    imageUrl: "/andos.png",
    content: `Pisau ini didapatkan oleh petugas dari tempat sampah Bara dan Luthfi. Saya barusan saja pergi ke rumah mereka untuk menegur sebab pisau yang dibuang tidak diberikan penutup apa-apa. Betapa bahayanya bagi para petugas apabila terinjak. Bara dan Luthfi sendiri mengaku mereka tidak mengetahui pisau itu milik siapa, tapi sepertinya itu hanya dikatakan agar mereka menghindari omelan saya.`,
    icon: WitnessIcon,
    characterId: "andos",
    isAlibi: false,
  },
  BARA: {
    type: "Seniman Street Art",
    title: "WAWANCARA 1",
    subtitle: "Seniman Street Art",
    imageUrl: "/bara.png",
    content: `Harus banget dijawab ya Pak? Kamis malam, Saya dan Luthfi keluar dari daerah Bendungan Hilir, Tanah Abang untuk mencari lokasi tagging sekitar pukul 00.00 WIB menggunakan mobil lama peninggalan Ibu saya. Kami keliling selama 1 jam untuk mencari lokasi. Sebenarnya ada beberapa spot yang kami lihat asik: Setia Budi, Kebayoran Lama, Kebayoran Baru, dan Palmerah. Tetapi, kami akhirnya memutuskan untuk melakukan tagging di kolong jembatan Kebayoran Baru, itu tempat biasa kami tagging dari sebelum-sebelumnya. Kami memang berada di kolong jembatan itu saat dini hari, tapi tujuannya murni untuk melakukan street art. Mengenai korban, saya tidak kaget dengan apa yang terjadi kepada Pak Yong dan Bu Malo. Ya kasihan sih, tapi mereka berdua ini memang cerewet jadi sudah pasti musuhnya banyak. Sialnya saya dan Luthfi adalah salah satu yang mereka cereweti, tapi tidak mungkinlah kami berani sebegitunya dengan yang sudah tua.`,
    icon: WitnessIcon,
    characterId: "bara",
    isAlibi: true,
  },
  BARA2: {
    type: "Seniman Street Art",
    title: "WAWANCARA 2",
    subtitle: "Seniman Street Art",
    imageUrl: "/bara.png",
    content: `Kings? Iya, betul itu merek piloks yang biasa saya pakai kalau tagging sama Luthfi. Kami memang pernah tagging di sana, tapi itu sudah seminggu yang lalu—karya yang dibuat juga besar sehingga pilok kami langsung habis saat digunakan di Palmerah dan kaleng-kaleng bekas itu langsung kami buang di tempat sampah terdekat. Sudah ya Detektif, setelah ini saya tidak akan menjawab pertanyaan lagi.`,
    icon: WitnessIcon,
    characterId: "bara",
    isAlibi: false,
  },
  RATU: {
    type: "Ratu Ningtyas Sekarya",
    title: "Ratu Ningtyas Sekarya",
    subtitle: "Ibu Rumah Tangga",
    imageUrl: "/ratu.png",
    content: `Aduh Detektif, jujur saja saya sudah tidak tahan lagi melihat kelakuan warga di Blok Pelita ini. Apalagi si Bara dan Luthfi itu. Saya ini istri Ketua RT, martabat keluarga kami itu nomor satu, dan dua orang itu jelas-jelas merusak apa yang suami saya telah pertahankan. Saya sudah berkali-kali melarang Abyaz bergaul dengan mereka karena mereka ini pengaruh buruk! Abyaz anak saya? Oh, dia anak yang baik. Biarpun penampilannya... yah, Detektif lihat sendiri lah, itu cuma fase sementara mahasiswa. Terkait kedatangan Pak Yong dan Bu Malo, saya tidak melihat mereka karena sedang arisan di rumah teman. Saya baru pulang pukul 21.00 WIB dan langsung tidur karena kelelahan. Kalau saja saya tahu mereka datang hanya untuk memarahi suami saya, saya pasti akan pasang badan.`,
    icon: WitnessIcon,
    characterId: "ratu",
    isAlibi: false,
  },
  ABYAZ: {
    type: "Abyaz Mahendra Wibowo",
    title: "Abyaz Mahendra Wibowo",
    subtitle: "Mahasiswa",
    imageUrl: "/abyaz.png",
    content: `Hm Pak Yong dan Bu Malo ya? Wah kemarin sempet kesini. Sempat terjadi argumen di antara Bapak, Pak Yong, dan Bu Malo perkara permasalahan Bara dan Luthfi. Saya mendengar nama saya disebut oleh Ibu Malo dan memutuskan untuk keluar. Tapi tidak terjadi apa-apa sih karena tidak lama mereka berdua keluar dari rumah pada pukul 20.00 WIB.
Soal Bara dan Luthfi, kami memang teman kecil. Tapi jujur, udah jarang ikut mereka. Sejak Bara kembali dari kampung dan tinggal di rumah peninggalan nyokapnya, mereka jadi makin liar. Awalnya cuma tagging atau vandalisme bareng di kolong jembatan buat lepas stres, tapi lama-lama mereka mainnya malah makin jauh. Makanya deh sekarang udah jarang ngikut mereka tagging lagi. Males aja kalau misal mereka sudah “tidur” sembarangan karena obat, saya yang repot.
`,
    icon: WitnessIcon,
    characterId: "abyaz",
    isAlibi: false,
  },
  ABYAZ2: {
    type: "WAWANCARA 2",
    title: "Abyaz Mahendra Wibowo",
    subtitle: "Mahasiswa",
    imageUrl: "/abyaz.png",
    content: `Hmm.. spray cans ya? Itu memang brand yang biasa saya gunakan sih, tapi sudah jarang dipakai karena ya saya sudah jarang juga tagging bareng Bara dan Luthfi. Mungkin punya mereka kali Pak.
`,
    icon: WitnessIcon,
    characterId: "abyaz",
    isAlibi: false,
  },
  DAMALI: {
    type: `Damali Nasya`,
    title: "WAWANCARA 1",
    subtitle: "Ibu Rumah Tangga",
    imageUrl: "/damali.png",
    content: `Malam waktu suami saya keluar menemui Pak RT, saya sudah merasa ada yang tidak beres. Ada aura merah pekat terpancar dari arah rumah Pak Rabhya, dan saya tidak asal bicara ya! Insting saya ini kuat.
Saya curiga sekali dengan Abyaz, anak Pak Rabhya itu... Jangan-jangan dia sakit hati karena ayahnya mau dilengserkan warga, termasuk oleh suami saya. Namanya saja hampir mirip, Rabhya dan Abyaz, pasti sifat juga tidak jauh berbeda!
Malam itu saya cuma bisa diam di ruang tamu, mencoba menetralisir aura jahat yang masuk sekaligus menunggu kepulangan suami saya. Saya sampai tidak berani menyalakan lampu. Sesekali saya mengintip dari balik gorden jendela depan. Nah, saat jam menunjukkan pukul 00.05 WIB, saya sempat mendengar ada dua kendaraan lewat dengan jarak waktu yang tidak jauh berbeda. Awalnya saya kira itu suami saya, tapi saya baru ingat kalau dia pergi tidak membawa mobil. Kalau saja saya keluar malam itu, mungkin saya juga dibunuh.
`,
    icon: WitnessIcon,
    characterId: "damali",
    isAlibi: false,
  },
  RABHYA: {
    type: "Rabhya Wibowo",
    title: "WAWANCARA 1",
    subtitle: "Tukang Furnitur Paruh Waktu",
    imageUrl: "/rabhya.png",
    content: "Saya tentu menyayangkan kejadian ini... Pak Yong dan Bu Malo adalah warga lama di Komplek Pelita. Kehilangan mereka tentu sangat berdampak, terutama bagi saya yang memikul tanggung jawab di lingkungan ini. Malam sebelum Pak Yong dan Bu Malo menghilang, mereka berdua sempat datang ke rumah untuk menemui saya. Mereka mendesak agar saya mengambil tindakan tegas untuk mengusir Bara dan Luthfi. Keduanya memang sudah lama dikenal problematik oleh warga. Beberapa hari lalu polisi bahkan datang ke komplek kami hanya untuk menanyakan soal mereka berdua, inilah puncaknya. Tapi, sebagai seseorang yang pernah bersumpah menjaga hukum dan negara, saya tidak bisa bertindak gegabah. Semua masih berupa dugaan, belum ada bukti sah. Saya jelaskan kepada mereka bahwa saya harus adil, suka atau tidak suka. Mereka kecewa, sempat marah sebelum akhirnya keluar dari rumah. Setelah mereka pergi... saya sudah tidak tahu lagi mereka ke mana.",
    icon: WitnessIcon,
    characterId: "rabhya",
    isAlibi: true,
  },
  RABHYA_2: {
    type: "Rabhya Wibowo",
    title: "WAWANCARA 2",
    subtitle: "Tukang Furnitur Paruh Waktu",
    imageUrl: "/rabhya.png",
    content: "Oh iya mengenai mobil yang di depan rumah kosong itu ya? Ha-ha- Saya lupa mobil itu disitu.. Sengaja saya letakkan sebab Andos biasanya pinjam jika ada kebutuhan mengenai kegiatan di TPS. Saya sangat mendukung Andos sepenuhnya sebagai ketua pengelola TPS di perumahan kami. Visi misi kami nyambung makanya saya selalu memastikan dapat memfasilitasi dengan sebaik-baiknya.",
    icon: WitnessIcon,
    characterId: "rabhya",
    isAlibi: false,
  },
  ADINATA: {
    type: "Adinata Agung",
    title: "WAWANCARA 1",
    subtitle: "Pebisnis",
    imageUrl: "/luthfi.png",
    content: "Malam Kamis hingga Jumat dini hari... benar, kami memang berada di tempat kejadian sekitar pukul 01.00 WIB. Situasi sekitar saat itu sepi sekali, makanya saya dan Bara memutuskan melakukan tagging disitu. Kami tagging sampai dengan pukul 03.00 WIB..? Kalau tidak salah jam segitu kami memutuskan untuk berhenti. Mohon maaf Detektif, tapi saya lupa banyak detail tentang malam itu karena efek alkohol. Seingat saya, kami fokus mencari tembok kosong untuk melakukan tagging di bawah jembatan di pukul yang saya tuturkan tadi. Jujur, saya sama sekali tidak tahu-menahu soal pembunuhan tersebut.",
    icon: WitnessIcon,
    characterId: "adinata",
    isAlibi: false,
  },
  LUTHFI: {
    type: "Cahaya Luthfi Darmawan",
    title: "WAWANCARA 1",
    subtitle: "Pebisnis",
    imageUrl: "/adinata.png",
    content: "Ya, tentu saja saya menyayangkan apa yang menimpa Pak Yong dan Bu Malo. Sangat disayangkan sekali. Mereka berdua adalah pendukung setia saya dan sangat vokal dalam menggalang suara untuk saya. Kamis sore itu sekitar pukul 17.30 WIB Pak Yong dan Bu Malo sempat ke rumah untuk membahas strategi menjelang pemilihan Ketua RT minggu depan, mereka berdua sangat antusias. Setelah itu, semalaman saya sibuk menyusun draf program kerja di ruang kerja saya. Saya tidak punya waktu untuk mengurus hal lain di luar persiapan pemilihan. Bapak tahu sendiri, warga sudah lelah dengan kepemimpinan yang sekarang. Tapi ya, mau bagaimana lagi?",
    icon: WitnessIcon,
    characterId: "luthfi",
    isAlibi: false,
  },
  CHANTIKA: {
    type: "Angelina Chantika",
    title: "WAWANCARA 1",
    subtitle: "Ibu Rumah Tangga",
    imageUrl: "/chantika.png",
    content: `Hmm, malam kejadian ya? Aduh Detektif, komplek ini tuh emang lagi panas-panasnya! Gosip yang paling kencang ya perselisihan Pak Yong dan Bu Malo sama anak-anak punk itu, si Bara dan Luthfi, soal isu obat-obatan. Nah, malam Kamis itu saya lihat sendiri Pak Yong sama Bu Malo datang ke rumah Pak Rabhya buat bahas mereka. Karena penasaran, saya sempatkan berhenti sebentar di depan pagar Pak RT buat menguping. Awalnya biasa saja, tapi lama-lama suaranya meninggi, kedengarannya argumen mereka memanas sekali. Karena saya merasa sudah dapat 'inti' gosipnya, sekitar pukul 19.45 WIB saya memutuskan pulang. Jadi saya nggak tahu deh tuh mereka keluar dari sana jam berapa, yang jelas pas saya tinggal sih mereka masih ribut di dalam.
Oh iya, ini mengingatkan saya soal satu hal lagi. Ada isu soal upaya pelengseran Pak Rabhya dari kursi Ketua RT. Penggeraknya itu lima orang: Pak Esman, Bu Tia, Pak Sodikin, Pak Yong, dan Bu Malo. Tapi anehnya, tiga orang pertama itu sekarang mendadak nggak tahu rimbanya ke mana. Sekarang tinggal Pak Yong sama Bu Malo yang paling vokal, apalagi minggu depan sudah mau pemilihan lagi dan Pak Rabhya memajukan dirinya kembali. Bagi saya sih Pak Rabhya orangnya baik-baik saja, cuma lima orang itu saja yang sepertinya punya dendam pribadi.
`,
    icon: WitnessIcon,
    characterId: "chantika",
    isAlibi: false,
  },
  DIMAS_PRAKASA_2: {
    type: "Saksi",
    title: "Dimas Prakasa",
    subtitle: "Suami",
    imageUrl: "/C005.webp",
    content: "Pernyataan dari Dimas Prakasa.",
    icon: WitnessIcon,
    characterId: "dimas",
    isAlibi: true,
    audioUrl: "/audio/dimas.mp3",
  },
  Larasati: {
    type: "Saksi",
    title: "Larasati",
    subtitle: "ART Keluarga",
    imageUrl: "/C007.webp",
    content: "Pernyataan dari Larasati.",
    icon: WitnessIcon,
    characterId: "larasati",
    isAlibi: true,
    audioUrl: "/audio/larasati.mp3",
  },
  Ibu_Lastri: {
    type: "Saksi",
    title: "Ibu Lastri",
    subtitle: "Tetangga",
    imageUrl: "/C008.webp",
    content: "Pernyataan dari Ibu Lastri.",
    icon: WitnessIcon,
    characterId: "lastri",
    isAlibi: true,
    audioUrl: "/audio/lastri.mp3",
  },
  Risa: {
    type: "Saksi",
    title: "Risa",
    subtitle: "Istri Arief",
    imageUrl: "/C009.webp",
    content: "Pernyataan dari Risa.",
    icon: WitnessIcon,
    characterId: "risa",
    isAlibi: true,
    audioUrl: "/audio/risa.mp3",
  },
  CCTV: {
    type: "Bukti",
    title: "CCTV",
    subtitle: "Rekaman Keamanan",
    imageUrl: "/C006.webp",
    content:
      "Rumah dua lantai yang terawat baik di area perumahan yang tenang. Tidak ada tanda-tanda masuk paksa. Tim forensik menemukan jejak pembersih lantai dengan aroma lemon yang kuat di area ruang tamu, tidak sesuai dengan produk pembersih yang biasa digunakan oleh asisten rumah tangga keluarga.",
    icon: EvidenceIcon,
  },
  FORENSICS_REPORT_A: {
    type: "Forensik",
    title: "Laporan Forensik Awal",
    subtitle: "Lab Kriminalistik Jakarta",
    imageUrl: "/forensics_report.png",
    content:
      "Korban, Helda, ditemukan meninggal akibat trauma benda tumpul di kepala bagian belakang. Waktu kematian diperkirakan antara pukul 23.00 WIB, 9 November dan 02.00 WIB, 10 November. Ditemukan juga sedikit residu tanah liat merah di bawah kuku korban yang tidak cocok dengan tanah di sekitar properti Pluit.",
    icon: ForensicsIcon,
  },
};

export const getGameData = (qrCode: string): GameDataItem | null => {
  const data = gameData[qrCode];
  if (!data) return null;
  return { id: qrCode, ...data };
};
